# Generated by Django 2.1.4 on 2018-12-03 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leis', '0002_auto_20181203_1626'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lei',
            options={'verbose_name': 'Lei', 'verbose_name_plural': 'Leis'},
        ),
    ]
