# Generated by Django 2.1.4 on 2018-12-03 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leis', '0003_auto_20181203_1752'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artigo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artigo', models.TextField(verbose_name='Artigo/Inciso')),
                ('number', models.IntegerField(blank=True, null=True, verbose_name='Numero')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('lei', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artigos', to='leis.Lei', verbose_name='Lei')),
            ],
            options={
                'verbose_name': 'Artigo',
                'verbose_name_plural': 'Artigos',
            },
        ),
    ]
