# Generated by Django 2.1.3 on 2018-12-04 11:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leis', '0004_artigo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marcacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_marcado', models.BooleanField(blank=True, default=False, verbose_name='Está Marcado?')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('artigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marcacaoLei', to='leis.Lei', verbose_name='Artigo')),
                ('lei', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marcacaoArtigos', to='leis.Lei', verbose_name='Lei')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marcacaoUsuario', to=settings.AUTH_USER_MODEL, verbose_name='marcacaoUsuário')),
            ],
        ),
    ]
