# Generated by Django 2.1.3 on 2018-12-04 14:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leis', '0005_marcacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marcacao',
            name='usuario',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='marcacaoUsuario', to=settings.AUTH_USER_MODEL, verbose_name='marcacaoUsuário'),
        ),
    ]
