# Generated by Django 2.1.3 on 2018-12-04 17:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leis', '0006_auto_20181204_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marcacao',
            name='artigo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marcacaoLei', to='leis.Artigo', verbose_name='Artigo'),
        ),
        migrations.AlterField(
            model_name='marcacao',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marcacaoUsuario', to=settings.AUTH_USER_MODEL, verbose_name='marcacaoUsuário'),
        ),
    ]
