# Generated by Django 2.1.4 on 2018-12-05 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leis', '0007_auto_20181204_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='marcacao',
            name='is_importante',
            field=models.BooleanField(blank=True, default=False, verbose_name='É importante?'),
        ),
        migrations.AddField(
            model_name='marcacao',
            name='votes',
            field=models.IntegerField(blank=True, default=0, verbose_name='Voto'),
        ),
    ]
