# Generated by Django 2.1.4 on 2018-12-05 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leis', '0008_auto_20181204_2349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marcacao',
            name='votes',
        ),
        migrations.AddField(
            model_name='marcacao',
            name='votos',
            field=models.IntegerField(blank=True, default=0, verbose_name='Votos'),
        ),
    ]
