# Generated by Django 2.1.3 on 2018-12-05 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leis', '0009_auto_20181204_2350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artigo',
            name='number',
        ),
        migrations.AddField(
            model_name='artigo',
            name='id_artigo_lei',
            field=models.IntegerField(blank=True, null=True, verbose_name='Artigo Lei'),
        ),
    ]
