# Generated by Django 2.1.4 on 2018-12-13 09:40

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('leis', '0012_artigo_is_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marcacao',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Content'),
        ),
    ]
