# Generated by Django 2.0.9 on 2018-12-13 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leis', '0013_lei_pacote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lei',
            name='pacote',
        ),
    ]
