# Generated by Django 2.1.4 on 2018-12-13 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacotes', '0003_pacote_lei'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacote',
            name='ativo',
            field=models.BooleanField(blank=True, default=False, verbose_name='Está ativo?'),
        ),
    ]
