# Generated by Django 2.1.4 on 2018-12-13 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leis', '0014_remove_lei_pacote'),
        ('pacotes', '0004_auto_20181213_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacote',
            name='leis',
            field=models.ManyToManyField(to='leis.Lei'),
        ),
    ]
