# Generated by Django 2.1.4 on 2018-12-13 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacotes', '0005_pacote_leis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pacote',
            name='lei',
        ),
    ]
