# Generated by Django 2.0.9 on 2018-12-14 17:41

from django.db import migrations, models
import medium.pacotes.models


class Migration(migrations.Migration):

    dependencies = [
        ('pacotes', '0006_remove_pacote_lei'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscricao',
            name='expire_date',
            field=models.DateField(default=medium.pacotes.models.get_deadline),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='tipo_pacote',
            field=models.IntegerField(blank=True, null=True, verbose_name='Artigo Lei'),
        ),
        migrations.AlterField(
            model_name='pacote',
            name='leis',
            field=models.ManyToManyField(related_name='lei_pacote', to='leis.Lei'),
        ),
    ]
