# Generated by Django 2.0.9 on 2018-12-14 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacotes', '0007_auto_20181214_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscricao',
            name='tipo_pacote',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Artigo Lei'),
        ),
    ]
